import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import classes from "./page.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
	<body className={inter.className}>
		<main className={classes.main}>
			<NavBar/>	
			{children}
		</main>
	</body>
    </html>
  );
}
